version: "3.2"
services:
  aiohttp-server:
    build: .
    container_name: aiohttp-server
    ports:
      - "8080:8080"
    command: >
      sh -c "python main.py"
    volumes:
      - .:/aiohttp_server
    depends_on:
      - postgres

  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4322
    ports:
      - "5432:5432"
    container_name: postgres


