version: "3.2"
services:
  aiohttp-server:
    build: .
    container_name: aiohttp-server
    ports:
      - "8080:8080"
    command: >
      sh -c "python main.py"
    volumes:
      - .:/aiohttp_server
    depends_on:
      - postgres

  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    container_name: postgres


